name: Continuous Integration with GitHub Actions

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - uses: go-semantic-release/action@v1
              with:
                  hooks: goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
