name: Continuous Integration with GitHub Actions

on:
    push:
        branches:
            - main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - uses: golangci/golangci-lint-action@v4
              with:
                  version: latest
                  args: --disable-all --enable gosimple

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: lint
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - uses: go-semantic-release/action@v1
              with:
                  hooks: goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
